/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ahmed m Fawzi
 */
public class Medicines extends javax.swing.JFrame {

    /**
     * Creates new form Medicines
     */
    public Medicines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jIDTxt = new javax.swing.JTextField();
        jPlaceTxt = new javax.swing.JTextField();
        jTimeTxt = new javax.swing.JTextField();
        jDataTxt = new javax.swing.JTextField();
        jPriceTxt = new javax.swing.JTextField();
        jCo_NameTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMedicinesTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jNumberTxt = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jTypeTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNeeded_MedicineTable = new javax.swing.JTable();
        jNNameTxt = new javax.swing.JTextField();
        jNCo_NameTxt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jNTypeTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jNIDTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jNNumberTxt = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1025, 509));

        jLabel1.setText("Medicine_Name");

        jLabel2.setText("Medicine_ID");

        jLabel3.setText("Medicine_Type");

        jLabel4.setText("Medicine_Place");

        jLabel5.setText("Medicine_Price");

        jLabel6.setText("Production Data");

        jLabel7.setText("Expirition Time");

        jLabel8.setText("Company Name");

        jIDTxt.setEnabled(false);

        jMedicinesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jMedicinesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMedicinesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jMedicinesTable);

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Updata");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Show All Medicines");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("Back>>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Medicine_Number ");

        jNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumberTxtActionPerformed(evt);
            }
        });

        jButton11.setText("Refresh");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCo_NameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTimeTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDataTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPriceTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPlaceTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTypeTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jIDTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNumberTxt))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTypeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPlaceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPriceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCo_NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Medicines", jPanel1);

        jLabel9.setText("Medicine_Name");

        jLabel10.setText("Medicine_Type");

        jLabel11.setText("Company_ Name");

        jNeeded_MedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jNeeded_MedicineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNeeded_MedicineTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jNeeded_MedicineTable);

        jButton6.setText("Insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Updata");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Show All Needed Medicine");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton10.setText("Back >>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel12.setText("Medicine_ID");

        jNIDTxt.setEnabled(false);

        jLabel14.setText("Medicine_number");

        jButton12.setText("Refresh");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNNameTxt)
                            .addComponent(jNCo_NameTxt)
                            .addComponent(jNTypeTxt)
                            .addComponent(jNIDTxt)
                            .addComponent(jNNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)))
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNCo_NameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Needed Medicine", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from medicine");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("med_name");
            dm.addColumn("med_id");
            dm.addColumn("med_type");
            dm.addColumn("med_place");
            dm.addColumn("med_price");
            dm.addColumn("med_pdata");
            dm.addColumn("med_etime");
            dm.addColumn("company_name");
            dm.addColumn("med_num");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3), set.getString(4),
                set.getString(5), set.getString(6), set.getString(7), set.getString(8),set.getString(9)};
                dm.addRow(r);
            }

            jMedicinesTable.setModel(dm);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMedicinesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMedicinesTableMouseClicked
        int row_num = jMedicinesTable.getSelectedRow();
        String name = jMedicinesTable.getValueAt(row_num, 0).toString();
        String id = jMedicinesTable.getValueAt(row_num, 1).toString();
        String type = jMedicinesTable.getValueAt(row_num, 2).toString();
        String place = jMedicinesTable.getValueAt(row_num, 3).toString();
        String price = jMedicinesTable.getValueAt(row_num, 4).toString();
        String pdate = jMedicinesTable.getValueAt(row_num, 5).toString();
        String etime = jMedicinesTable.getValueAt(row_num, 6).toString();
        String co_name = jMedicinesTable.getValueAt(row_num, 7).toString();
        String number = jMedicinesTable.getValueAt(row_num, 8).toString();
        
        jNameTxt.setText(name);
        jIDTxt.setText(id);
        jTypeTxt.setText(type);
        jPlaceTxt.setText(place);
        jPriceTxt.setText(price);
        jDataTxt.setText(pdate);
        jTimeTxt.setText(etime);
        jCo_NameTxt.setText(co_name);
        jNumberTxt.setText(number);
        
    }//GEN-LAST:event_jMedicinesTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into medicine(medicine.med_name,medicine.med_type,medicine.med_place,medicine.med_price,medicine.med_pdata,medicine.med_etime,medicine.company_name,medicine.med_num) values(?,?,?,?,?,?,?,?)");
            String name = jNameTxt.getText();
            String type = jTypeTxt.getText();
            String place = jPlaceTxt.getText();
            String price = jPriceTxt.getText();
            String pdata = jDataTxt.getText();
            String etime = jTimeTxt.getText();
            String co_name = jCo_NameTxt.getText();
            String number = jNumberTxt.getText();
            stmt.setString(1, name);
            stmt.setString(2, type);
            stmt.setString(3, place);
            stmt.setString(4, price);
            stmt.setString(5, pdata);
            stmt.setString(6, etime);
            stmt.setString(7, co_name);
            stmt.setString(8, number);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insertion Success");
            jNameTxt.setText("");
            jIDTxt.setText("");
            jTypeTxt.setText("");
            jPlaceTxt.setText("");
            jPriceTxt.setText("");
            jDataTxt.setText("");
            jTimeTxt.setText("");
            jCo_NameTxt.setText("");
            jNumberTxt.setText("");
            jButton4ActionPerformed(evt);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("update medicine set med_name=?,med_type=?,med_place=?,med_price=?,med_pdata=?,med_etime=?,company_name=?,med_num=? where med_id=?");
            String name = jNameTxt.getText();
            String type = jTypeTxt.getText();
            String place = jPlaceTxt.getText();
            String price = jPriceTxt.getText();
            String pdata = jDataTxt.getText();
            String etime = jTimeTxt.getText();
            String co_name = jCo_NameTxt.getText();
            String number=jNumberTxt.getText();
            String id = jIDTxt.getText();
            stmt.setString(1, name);
            stmt.setString(2, type);
            stmt.setString(3, place);
            stmt.setString(4, price);
            stmt.setString(5, pdata);
            stmt.setString(6, etime);
            stmt.setString(7, co_name);
            stmt.setString(8, number);
            stmt.setString(9, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update Success");
            jNameTxt.setText("");
            jIDTxt.setText("");
            jTypeTxt.setText("");
            jPlaceTxt.setText("");
            jPriceTxt.setText("");
            jDataTxt.setText("");
            jTimeTxt.setText("");
            jCo_NameTxt.setText("");
            jNumberTxt.setText("");
            jButton4ActionPerformed(evt);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("delete from medicine where med_id=?");
            String id = jIDTxt.getText();
            stmt.setString(1, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "deletion Success");
            
            jNameTxt.setText("");
            jIDTxt.setText("");
            jTypeTxt.setText("");
            jPlaceTxt.setText("");
            jPriceTxt.setText("");
            jDataTxt.setText("");
            jTimeTxt.setText("");
            jCo_NameTxt.setText("");
            jNumberTxt.setText("");
            jButton4ActionPerformed(evt);


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from needed_medicine");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("nmed_name");
            dm.addColumn("nmed_id");
            dm.addColumn("nmed_type");
            dm.addColumn("ncompany_name");
            dm.addColumn("nmed_num");

            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2), set.getString(3),set.getString(4),set.getString(5)};
                dm.addRow(r);
            }

            jNeeded_MedicineTable.setModel(dm);

        } catch (SQLException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jNeeded_MedicineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNeeded_MedicineTableMouseClicked
        int row_num = jNeeded_MedicineTable.getSelectedRow();
        String name = jNeeded_MedicineTable.getValueAt(row_num, 0).toString();
        String id = jNeeded_MedicineTable.getValueAt(row_num, 1).toString();
        String type = jNeeded_MedicineTable.getValueAt(row_num, 2).toString();
        String co_name = jNeeded_MedicineTable.getValueAt(row_num, 3).toString();
        String number = jNeeded_MedicineTable.getValueAt(row_num, 4).toString();
        jNNameTxt.setText(name);
        jNIDTxt.setText(id);
        jNTypeTxt.setText(type);
        jNCo_NameTxt.setText(co_name);
        jNNumberTxt.setText(number);
    }//GEN-LAST:event_jNeeded_MedicineTableMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into needed_medicine(needed_medicine.nmed_name,needed_medicine.nmed_type,needed_medicine.ncompany_name,needed_medicine.nmed_num) values(?,?,?,?)");
            String name = jNNameTxt.getText();
            String type = jNTypeTxt.getText();
            String co_name = jNCo_NameTxt.getText();
            String number = jNNumberTxt.getText();
            
            stmt.setString(1, name);
            stmt.setString(2, type);
            stmt.setString(3, co_name);
            stmt.setString(4, number);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insertion Success");
            jNNameTxt.setText("");
            jNIDTxt.setText("");
            jNTypeTxt.setText("");
            jNCo_NameTxt.setText("");
            jNNumberTxt.setText("");
            jButton9ActionPerformed(evt);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("update needed_medicine set nmed_name=?, nmed_type=?,ncompany_name=?,nmed_num=? where nmed_id=?");
            String name = jNNameTxt.getText();
            String type = jNTypeTxt.getText();
            String co_name = jNCo_NameTxt.getText();
            String number = jNNumberTxt.getText();
            String id = jNIDTxt.getText();
            stmt.setString(1, name);
            stmt.setString(2, type);
            stmt.setString(3, co_name);
            stmt.setString(4, number );
            stmt.setString(5, id );
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update Success");
            jNNameTxt.setText("");
            jNIDTxt.setText("");
            jNTypeTxt.setText("");
            jNCo_NameTxt.setText("");
            jNNumberTxt.setText("");
            jButton9ActionPerformed(evt);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pharmacy", "root", "root");
            PreparedStatement stmt = con.prepareStatement("delete from needed_medicine where nmed_id=?");
            String id = jNIDTxt.getText();
            stmt.setString(1, id);
            jCo_NameTxt.setText(jNCo_NameTxt.getText());
            jNameTxt.setText(jNNameTxt.getText());
            jTypeTxt.setText(jNTypeTxt.getText());
            jNumberTxt.setText(jNNumberTxt.getText());
            jPlaceTxt.setText("");
            jPriceTxt.setText("");
            jIDTxt.setText("");
            jDataTxt.setText("");
            jTimeTxt.setText("");
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "deletion Success");
            jButton9ActionPerformed(evt);
            jNNameTxt.setText("");
            jNIDTxt.setText("");
            jNTypeTxt.setText("");
            jNCo_NameTxt.setText("");
            jNNumberTxt.setText("");
            
            
            


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible (false);
        Main_frame m = new Main_frame ();
        m.setVisible (true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.setVisible (false);
        Main_frame m = new Main_frame ();
        m.setVisible (true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            jNameTxt.setText("");
            jIDTxt.setText("");
            jTypeTxt.setText("");
            jPlaceTxt.setText("");
            jPriceTxt.setText("");
            jDataTxt.setText("");
            jTimeTxt.setText("");
            jCo_NameTxt.setText("");
            jNumberTxt.setText("");
            jButton4ActionPerformed(evt);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            jNNameTxt.setText("");
            jNIDTxt.setText("");
            jNTypeTxt.setText("");
            jNCo_NameTxt.setText("");
            jNNumberTxt.setText("");
            jButton9ActionPerformed(evt);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumberTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jCo_NameTxt;
    private javax.swing.JTextField jDataTxt;
    private javax.swing.JTextField jIDTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTable jMedicinesTable;
    private javax.swing.JTextField jNCo_NameTxt;
    private javax.swing.JTextField jNIDTxt;
    private javax.swing.JTextField jNNameTxt;
    private javax.swing.JTextField jNNumberTxt;
    private javax.swing.JTextField jNTypeTxt;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JTable jNeeded_MedicineTable;
    private javax.swing.JTextField jNumberTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPlaceTxt;
    private javax.swing.JTextField jPriceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTimeTxt;
    private javax.swing.JTextField jTypeTxt;
    // End of variables declaration//GEN-END:variables
}
